//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C2G.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reserva()
        {
            this.ReservaAccesorio = new HashSet<ReservaAccesorio>();
            this.ReservaServicio = new HashSet<ReservaServicio>();
            this.UsuarioReserva = new HashSet<UsuarioReserva>();
        }
    
        public int id_reserva { get; set; }
        public System.DateTime fecha_hora_reserva { get; set; }
        public int id_auto { get; set; }
        public string lugar_retiro { get; set; }
        public System.DateTime fecha_retiro { get; set; }
        public System.TimeSpan hora_retiro { get; set; }
        public string lugar_devolucion { get; set; }
        public System.DateTime fecha_devolucion { get; set; }
        public System.TimeSpan hora_devolucion { get; set; }
        public decimal cargos_servicios { get; set; }
        public decimal cargos_accesorios { get; set; }
        public decimal cargos_total { get; set; }
        public string estado { get; set; }
        public Nullable<int> descuento { get; set; }
    
        public virtual Auto Auto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservaAccesorio> ReservaAccesorio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservaServicio> ReservaServicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioReserva> UsuarioReserva { get; set; }
    }
}
