//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C2G.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolOperacion
    {
        public int id_rol_operacion { get; set; }
        public int id_rol { get; set; }
        public int id_operacion { get; set; }
    
        public virtual Operacion Operacion { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
